In [1]:
import pandas as pd
import numpy as np

In [2]:
cov = pd.read_csv('annual_cov.csv')

In [7]:
cov

ticker       gnk      bbby      hcci       skm        cs       azn  \
0    gnk  0.690032  0.140960  0.160924  0.034631  0.096489  0.044800   
1   bbby  0.140960  2.594074  0.180361  0.051857  0.103711  0.026991   
2   hcci  0.160924  0.180361  0.412413  0.039834  0.099506  0.043296   
3    skm  0.034631  0.051857  0.039834  0.088998  0.029604  0.017526   
4     cs  0.096489  0.103711  0.099506  0.029604  0.100117  0.026916   
5    azn  0.044800  0.026991  0.043296  0.017526  0.026916  0.092751   
6   nvda  0.147940  0.205861  0.141264  0.049475  0.098560  0.068286   
7   epac  0.111476  0.135409  0.120823  0.029768  0.065451  0.027263   

       nvda      epac  
0  0.147940  0.111476  
1  0.205861  0.135409  
2  0.141264  0.120823  
3  0.049475  0.029768  
4  0.098560  0.065451  
5  0.068286  0.027263  
6  0.559329  0.103007  
7  0.103007  0.159152

In [8]:
cov = cov.set_index('ticker')

In [23]:
a = cov.to_numpy()

In [24]:
b = [0,0,0,0,0,0,0,0]

In [25]:
w =np.linalg.lstsq(a, b)

/var/folders/qs/08lrvdq116j2p_7gkyvmdryw0000gn/T/ipykernel_8088/554651218.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w =np.linalg.lstsq(a, b)


In [26]:
w

(array([0., 0., 0., 0., 0., 0., 0., 0.]),
 array([], dtype=float64),
 8,
 array([2.66725851, 0.91600682, 0.47074042, 0.32233444, 0.11300637,
        0.08447597, 0.07239152, 0.05065153]))

In [28]:
w[3]

array([2.66725851, 0.91600682, 0.47074042, 0.32233444, 0.11300637,
       0.08447597, 0.07239152, 0.05065153])

In [31]:
#expected return
mean_return = pd.read_csv('sample_mean_daily_vector.csv')

In [33]:
mean_return = mean_return.drop(columns=['Unnamed: 0'])

In [40]:
mean_return

gnk      bbby      hcci       skm        cs       azn      nvda  \
0  0.000935  0.000906  0.000732 -0.000369 -0.000758  0.000624  0.001311   

       epac  
0  0.000008

In [41]:
r = mean_return.to_numpy()

In [44]:
weights = w[3]

In [45]:
weights

array([2.66725851, 0.91600682, 0.47074042, 0.32233444, 0.11300637,
       0.08447597, 0.07239152, 0.05065153])

In [46]:
np.transpose(weights)

array([2.66725851, 0.91600682, 0.47074042, 0.32233444, 0.11300637,
       0.08447597, 0.07239152, 0.05065153])

In [75]:
r[0].dot(weights)

0.003611527652698037

In [53]:
for i in weights:
    print(i)

2.667258508835549
0.9160068240838383
0.4707404208022636
0.32233444040355497
0.11300637465099556
0.08447596529791658
0.07239152217831189
0.05065153126914417


In [80]:
summation = 0.00
for i in range(len(r[0])):
    value = weights[i]*r[0][i]
    print(r[0][i], weights[i])
    summation += value

0.0009349088039275 2.667258508835549
0.0009059668773281 0.9160068240838383
0.0007316616912819 0.4707404208022636
-0.0003687380085407 0.32233444040355497
-0.0007575196479243 0.11300637465099556
0.0006242154248758 0.08447596529791658
0.0013110541525029 0.07239152217831189
8.10870689692216e-06 0.05065153126914417


In [81]:
summation

0.003611527652698037

In [82]:
weights

array([2.66725851, 0.91600682, 0.47074042, 0.32233444, 0.11300637,
       0.08447597, 0.07239152, 0.05065153])

In [84]:
a_w = a.dot(weights)

In [86]:
a_w.dot(weights)

8.813930526356497

In [87]:
weights.dot(a_w)

8.813930526356497

In [88]:
np.sqrt(8.813)

2.968669735757078

In [93]:
weights.transpose().reshape(8,1)

array([[2.66725851],
       [0.91600682],
       [0.47074042],
       [0.32233444],
       [0.11300637],
       [0.08447597],
       [0.07239152],
       [0.05065153]])

In [96]:
gradient = cov_matrix.dot(weights)

In [97]:
gradient

array([2.08757357, 2.8895453 , 0.8326662 , 0.19722614, 0.4327818 ,
       0.18744822, 0.72822467, 0.51306015])

In [99]:
gradient = gradient.transpose().reshape(8,1)

In [100]:
gradient

array([[2.08757357],
       [2.8895453 ],
       [0.8326662 ],
       [0.19722614],
       [0.4327818 ],
       [0.18744822],
       [0.72822467],
       [0.51306015]])